<a href="https://colab.research.google.com/github/ValdazoAmerico/tensorflow-embedding/blob/main/embedding_for_word_corpus_rnn_in_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
x = ['I am very haypp today','No, I do not like the movie']
y = [1,0]

In [ ]:
tokenizer = Tokenizer(num_words=20)

In [ ]:
tokenizer.fit_on_texts(x)

In [ ]:
sequences = tokenizer.texts_to_sequences(x)

In [ ]:
word_index = tokenizer.word_index
print(tokenizer.word_index)
print('Found %s unique tokens.' % len(word_index))

{'i': 1, 'am': 2, 'very': 3, 'haypp': 4, 'today': 5, 'no': 6, 'do': 7, 'not': 8, 'like': 9, 'the': 10, 'movie': 11}
Found 11 unique tokens.


In [ ]:
print(sequences)

[[1, 2, 3, 4, 5], [6, 1, 7, 8, 9, 10, 11]]


In [ ]:
#Identify max lenght of reviews
max_length = 0
for review_number in range(len(sequences)):
  numberofwords=len(sequences[review_number])
  if (numberofwords) > (max_length):
    max_length = numberofwords
print(max_length)

7


In [ ]:
#Padding the sequence for shorter reviews
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
data = pad_sequences(sequences, maxlen=max_length)
y = np.asarray(y)
print(data)
print('The Shape Of Data Tensor:', data.shape)
print('Shape of label tensor:', y.shape)

[[ 0  0  1  2  3  4  5]
 [ 6  1  7  8  9 10 11]]
The Shape Of Data Tensor: (2, 7)
Shape of label tensor: (2,)


In [ ]:
from tensorflow.keras.models import *
from tensorflow.keras.layers import *

total_words = len(word_index)+1
embedding_dim = 5
#define model
model = Sequential()
model.add(Embedding(total_words, embedding_dim, input_length=max_length,name='embedding_layer'))
model.add(SimpleRNN(128, activation='relu',return_sequences=True,name='rnn1'))
model.add(SimpleRNN(256, activation='relu',name='rnn2'))
model.add(Dense(1,activation='sigmoid'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_layer (Embedding)  (None, 7, 5)              60        
_________________________________________________________________
rnn1 (SimpleRNN)             (None, 7, 128)            17152     
_________________________________________________________________
rnn2 (SimpleRNN)             (None, 256)               98560     
_________________________________________________________________
dense (Dense)                (None, 1)                 257       
Total params: 116,029
Trainable params: 116,029
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
from keras.optimizers import *
#compile network
opt = SGD(lr=0.01,decay=1e-6)
model.compile(loss="binary_crossentropy",optimizer=opt, metrics=['accuracy'])
#fit network
model.fit(data, y, epochs=10, verbose=1)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.6948 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6925 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6906 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6888 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6871 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6855 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6840 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6827 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6815 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6804 - accuracy: 1.0000


In [ ]:
embeddings=model.get_weights()
print('Embedding Layer weight shape:', embeddings[0].shape)
print('Embedding Layer weight:', embeddings[0])

Embedding Layer weight shape: (12, 5)
Embedding Layer weight: [[-0.01173312 -0.02282069 -0.04649848 -0.00152503 -0.00179871]
 [ 0.00630259  0.04307024 -0.04247494  0.04338709  0.0146789 ]
 [ 0.04338428  0.03703294 -0.02043612  0.00047711  0.03013818]
 [-0.03176136 -0.03866009  0.0269333   0.02723563  0.02137726]
 [ 0.04569173  0.01422444 -0.02841561  0.02667941 -0.00092241]
 [-0.05042855 -0.00063094 -0.00641835  0.02358894 -0.00793879]
 [ 0.0153012   0.03954896  0.02716045 -0.00551824 -0.05040776]
 [ 0.01725877 -0.03577626 -0.01754079 -0.01732745 -0.01554221]
 [ 0.02630043  0.02198145 -0.00041428 -0.02054566  0.00275576]
 [-0.0301897  -0.03188618  0.02451312  0.04927035 -0.02066628]
 [ 0.03661839  0.02412095  0.04819538 -0.02283391 -0.02910481]
 [ 0.02777234 -0.02258898  0.00635848 -0.03772121  0.00537035]]
